CREATE TABLE users(
	id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
	email VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
	PASSWORD VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
	remember_token VARCHAR(100) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	`updated_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	CONSTRAINT unique_username UNIQUE (username),
	CONSTRAINT unique_email UNIQUE (email)
)ENGINE=INNODB;